feat(asset-index): implement complete withdrawal
ChainSafe/PINT pull request #79
Opened 2021-05-18 08:59 UTC by mattsse

## Changes

- implements the complete withdrawal extrinsic 

## Tests

```

```

## Issues

- Closes #27 
- Related #75 #76

2021-05-18 13:02 UTC, clearloop requested changes
* We need to separate these nests, really strange here LOL
* Break loop after `all_withdraw = false`
* No tests provided

2021-05-18 13:25 UTC, mattsse commented on pallets/asset-index/src/lib.rs
> +                if let Some(pending) = maybe_pending.take() {
Agreed, makes sense to issue an error if nothing to withdraw

2021-05-18 13:27 UTC, mattsse commented on pallets/asset-index/src/lib.rs
> +                                            all_withdrawn = false;
I think we should still process all assets that we can move to a `Withdrawn` state, so we actually need to iterate over all, this flag merely marks whether we can now remove the whole `Redemption` struct

2021-05-25 10:17 UTC, mattsse commented
> * Break loop after `all_withdraw = false`
We should continue unbonding every single asset, this is merely a maker whether we can close this pending withdrawal.
> * No tests provided
Follow up on #31

2021-06-07 11:00 UTC, mattsse commented
The are still some code paths that may change once the bonding/unbonding procedures and states are integrated with XCM

2021-06-07 11:31 UTC, clearloop approved these changes
One last thing is `withdraw` and `complete_withdraw` are easy to confuse, it would be better if we figure out another function name

2021-06-07 11:34 UTC, merged